version: '3.8'

services:
    nginx:
        container_name: domencheck_nginx
        image: nginx:alpine
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel-network

    app:
        container_name: domencheck_app
        build: .
        depends_on:
            - db
        volumes:
            - ./:/var/www
        networks:
            - laravel-network


    db:
        container_name: domencheck_db
        image: mysql:8
        restart: always
        ports:
            - "3307:3306"
        environment:
            MYSQL_DATABASE: domencheck
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - domencheck_db:/var/lib/mysql
        networks:
            - laravel-network

    domencheck_node:
        container_name: domencheck_node
        image: node:20
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel-network
        command: bash -c "npm install && npm run build"


networks:
    laravel-network:
        driver: bridge

volumes:
    domencheck_db:
